export const ucrmErrors = {
  REQUEST_INVALID_PER_TRANSPORT_SPEC: 100,
  REQUEST_PAYLOAD_UNKNOWN_APPID: 101,
  REQUEST_PAYLOAD_UNKNOWN_APPVERSION: 102,
  REQUEST_PAYLOAD_UNKNOWN_SCHEMAID: 103,
  REQUEST_PAYLOAD_INVALID_PER_APP_SPEC: 104,
  REQUEST_PAYLOAD_INVALID_JSON: 105,
  REGISTRY_UNKNOWN_ID: 200,
  RESPONSE_INVALID_PER_TRANSPORT_SPEC: 500,
}