name: Erstellt ein UCRI2-Release

on:
  push:
    tags:
      - 'v*.*.*' # Löst den Workflow aus, wenn ein Tag wie v1.0.0 oder v1.2.3 gepusht wird

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Code auschecken
      uses: actions/checkout@v4

    - name: Release-Dateien erzeugen
      run: |
        echo "Erzeuge Dateien für Upload"

        zip -r ucri2-api-${{ github.ref_name }}.zip api/ -x "*.zip"

        zip -r ucri2-apps-${{ github.ref_name }}.zip apps/ -x "*.zip"

        zip -r ucri2-all-${{ github.ref_name }}.zip . -x "*.zip"

        sha256sum *.zip > SHA256SUMS

        echo "Alle Dateien erzeugt."

    - name: Release erstellen oder abrufen
      id: create_release
      uses: ncipollo/release-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ github.ref }}
        name: Release ${{ github.ref_name }}
        draft: true
        prerelease: true
        allowUpdates: true
        artifacts: "ucri2-*-${{ github.ref_name }}.zip,SHA256SUMS"
