on: push
name: Validate API
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: Validate OpenAPI definition
      uses: char0n/swagger-editor-validate@v1
      with:
        definition-file: api/crm/0.1/crm.yaml