on: push
name: Validate API
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
    - name: Check out repository code
      uses: actions/checkout@v4
    - name: swagger-validator
      uses: mbowman100/swagger-validator-action@master
      with:
        files: api/crm/0.1/crm.yaml